// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xtothreshold.h"

extern XTothreshold_Config XTothreshold_ConfigTable[];

XTothreshold_Config *XTothreshold_LookupConfig(u16 DeviceId) {
	XTothreshold_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XTOTHRESHOLD_NUM_INSTANCES; Index++) {
		if (XTothreshold_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XTothreshold_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XTothreshold_Initialize(XTothreshold *InstancePtr, u16 DeviceId) {
	XTothreshold_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XTothreshold_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XTothreshold_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

