// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XTOTHRESHOLD_H
#define XTOTHRESHOLD_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xtothreshold_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_BaseAddress;
} XTothreshold_Config;
#endif

typedef struct {
    u32 Control_BaseAddress;
    u32 IsReady;
} XTothreshold;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XTothreshold_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XTothreshold_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XTothreshold_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XTothreshold_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XTothreshold_Initialize(XTothreshold *InstancePtr, u16 DeviceId);
XTothreshold_Config* XTothreshold_LookupConfig(u16 DeviceId);
int XTothreshold_CfgInitialize(XTothreshold *InstancePtr, XTothreshold_Config *ConfigPtr);
#else
int XTothreshold_Initialize(XTothreshold *InstancePtr, const char* InstanceName);
int XTothreshold_Release(XTothreshold *InstancePtr);
#endif

void XTothreshold_Start(XTothreshold *InstancePtr);
u32 XTothreshold_IsDone(XTothreshold *InstancePtr);
u32 XTothreshold_IsIdle(XTothreshold *InstancePtr);
u32 XTothreshold_IsReady(XTothreshold *InstancePtr);
void XTothreshold_EnableAutoRestart(XTothreshold *InstancePtr);
void XTothreshold_DisableAutoRestart(XTothreshold *InstancePtr);

void XTothreshold_SetCols(XTothreshold *InstancePtr, u32 Data);
u32 XTothreshold_GetCols(XTothreshold *InstancePtr);
void XTothreshold_SetRows(XTothreshold *InstancePtr, u32 Data);
u32 XTothreshold_GetRows(XTothreshold *InstancePtr);

void XTothreshold_InterruptGlobalEnable(XTothreshold *InstancePtr);
void XTothreshold_InterruptGlobalDisable(XTothreshold *InstancePtr);
void XTothreshold_InterruptEnable(XTothreshold *InstancePtr, u32 Mask);
void XTothreshold_InterruptDisable(XTothreshold *InstancePtr, u32 Mask);
void XTothreshold_InterruptClear(XTothreshold *InstancePtr, u32 Mask);
u32 XTothreshold_InterruptGetEnabled(XTothreshold *InstancePtr);
u32 XTothreshold_InterruptGetStatus(XTothreshold *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
