// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xtothreshold.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XTothreshold_CfgInitialize(XTothreshold *InstancePtr, XTothreshold_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XTothreshold_Start(XTothreshold *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTothreshold_ReadReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_AP_CTRL) & 0x80;
    XTothreshold_WriteReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XTothreshold_IsDone(XTothreshold *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTothreshold_ReadReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XTothreshold_IsIdle(XTothreshold *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTothreshold_ReadReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XTothreshold_IsReady(XTothreshold *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTothreshold_ReadReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XTothreshold_EnableAutoRestart(XTothreshold *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTothreshold_WriteReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_AP_CTRL, 0x80);
}

void XTothreshold_DisableAutoRestart(XTothreshold *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTothreshold_WriteReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_AP_CTRL, 0);
}

void XTothreshold_SetCols(XTothreshold *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTothreshold_WriteReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_COLS_DATA, Data);
}

u32 XTothreshold_GetCols(XTothreshold *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTothreshold_ReadReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_COLS_DATA);
    return Data;
}

void XTothreshold_SetRows(XTothreshold *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTothreshold_WriteReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_ROWS_DATA, Data);
}

u32 XTothreshold_GetRows(XTothreshold *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTothreshold_ReadReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_ROWS_DATA);
    return Data;
}

void XTothreshold_InterruptGlobalEnable(XTothreshold *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTothreshold_WriteReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_GIE, 1);
}

void XTothreshold_InterruptGlobalDisable(XTothreshold *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTothreshold_WriteReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_GIE, 0);
}

void XTothreshold_InterruptEnable(XTothreshold *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XTothreshold_ReadReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_IER);
    XTothreshold_WriteReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_IER, Register | Mask);
}

void XTothreshold_InterruptDisable(XTothreshold *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XTothreshold_ReadReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_IER);
    XTothreshold_WriteReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_IER, Register & (~Mask));
}

void XTothreshold_InterruptClear(XTothreshold *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTothreshold_WriteReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_ISR, Mask);
}

u32 XTothreshold_InterruptGetEnabled(XTothreshold *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTothreshold_ReadReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_IER);
}

u32 XTothreshold_InterruptGetStatus(XTothreshold *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTothreshold_ReadReg(InstancePtr->Control_BaseAddress, XTOTHRESHOLD_CONTROL_ADDR_ISR);
}

