# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold.xdc

# IP: ip/toThreshold_ap_dadd_3_full_dsp_64/toThreshold_ap_dadd_3_full_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==toThreshold_ap_dadd_3_full_dsp_64 || ORIG_REF_NAME==toThreshold_ap_dadd_3_full_dsp_64}]

# IP: ip/toThreshold_ap_dcmp_0_no_dsp_64/toThreshold_ap_dcmp_0_no_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==toThreshold_ap_dcmp_0_no_dsp_64 || ORIG_REF_NAME==toThreshold_ap_dcmp_0_no_dsp_64}]

# IP: ip/toThreshold_ap_ddiv_29_no_dsp_64/toThreshold_ap_ddiv_29_no_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==toThreshold_ap_ddiv_29_no_dsp_64 || ORIG_REF_NAME==toThreshold_ap_ddiv_29_no_dsp_64}]

# IP: ip/toThreshold_ap_dmul_4_max_dsp_64/toThreshold_ap_dmul_4_max_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==toThreshold_ap_dmul_4_max_dsp_64 || ORIG_REF_NAME==toThreshold_ap_dmul_4_max_dsp_64}]

# IP: ip/toThreshold_ap_dsub_3_full_dsp_64/toThreshold_ap_dsub_3_full_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==toThreshold_ap_dsub_3_full_dsp_64 || ORIG_REF_NAME==toThreshold_ap_dsub_3_full_dsp_64}]

# IP: ip/toThreshold_ap_sitodp_4_no_dsp_32/toThreshold_ap_sitodp_4_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==toThreshold_ap_sitodp_4_no_dsp_32 || ORIG_REF_NAME==toThreshold_ap_sitodp_4_no_dsp_32}]

# IP: ip/toThreshold_ap_uitodp_4_no_dsp_8/toThreshold_ap_uitodp_4_no_dsp_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==toThreshold_ap_uitodp_4_no_dsp_8 || ORIG_REF_NAME==toThreshold_ap_uitodp_4_no_dsp_8}]
