# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/project.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip c:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/project.srcs/sources_1/ip/toThreshold_ap_dadd_3_full_dsp_64/toThreshold_ap_dadd_3_full_dsp_64.xci
set_property is_locked true [get_files c:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/project.srcs/sources_1/ip/toThreshold_ap_dadd_3_full_dsp_64/toThreshold_ap_dadd_3_full_dsp_64.xci]

read_ip c:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/project.srcs/sources_1/ip/toThreshold_ap_dcmp_0_no_dsp_64/toThreshold_ap_dcmp_0_no_dsp_64.xci
set_property is_locked true [get_files c:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/project.srcs/sources_1/ip/toThreshold_ap_dcmp_0_no_dsp_64/toThreshold_ap_dcmp_0_no_dsp_64.xci]

read_ip c:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/project.srcs/sources_1/ip/toThreshold_ap_ddiv_29_no_dsp_64/toThreshold_ap_ddiv_29_no_dsp_64.xci
set_property is_locked true [get_files c:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/project.srcs/sources_1/ip/toThreshold_ap_ddiv_29_no_dsp_64/toThreshold_ap_ddiv_29_no_dsp_64.xci]

read_ip c:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/project.srcs/sources_1/ip/toThreshold_ap_dmul_4_max_dsp_64/toThreshold_ap_dmul_4_max_dsp_64.xci
set_property is_locked true [get_files c:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/project.srcs/sources_1/ip/toThreshold_ap_dmul_4_max_dsp_64/toThreshold_ap_dmul_4_max_dsp_64.xci]

read_ip c:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/project.srcs/sources_1/ip/toThreshold_ap_dsub_3_full_dsp_64/toThreshold_ap_dsub_3_full_dsp_64.xci
set_property is_locked true [get_files c:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/project.srcs/sources_1/ip/toThreshold_ap_dsub_3_full_dsp_64/toThreshold_ap_dsub_3_full_dsp_64.xci]

read_ip c:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/project.srcs/sources_1/ip/toThreshold_ap_sitodp_4_no_dsp_32/toThreshold_ap_sitodp_4_no_dsp_32.xci
set_property is_locked true [get_files c:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/project.srcs/sources_1/ip/toThreshold_ap_sitodp_4_no_dsp_32/toThreshold_ap_sitodp_4_no_dsp_32.xci]

read_ip c:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/project.srcs/sources_1/ip/toThreshold_ap_uitodp_4_no_dsp_8/toThreshold_ap_uitodp_4_no_dsp_8.xci
set_property is_locked true [get_files c:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/project.srcs/sources_1/ip/toThreshold_ap_uitodp_4_no_dsp_8/toThreshold_ap_uitodp_4_no_dsp_8.xci]

read_verilog -library xil_defaultlib {
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_borderInterpolate.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_Dilate_0_0_1080_1920_s_k_buf_0_val_0.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_dadd_64ns_64ns_64_5_full_dsp.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_dcmp_64ns_64ns_1_1.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_ddiv_64ns_64ns_64_31.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_dmul_64ns_64ns_64_6_max_dsp.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_dsub_64ns_64ns_64_5_full_dsp.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_Filter2D.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_Filter2D_1.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_Loop_LineBufferLoop_proc_lineBuffer_val_0.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_sitodp_32ns_64_6.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_uitodp_8ns_64_6.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_absvalueMat_data_stream_0_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_angleMat_data_stream_0_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_blurMat_cols_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_blurMat_data_stream_0_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_blurMat_rows_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_blursobelxMat_cols_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_blursobelxMat_cols_V_channel.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_blursobelxMat_data_stream_0_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_blursobelxMat_rows_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_blursobelxMat_rows_V_channel.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_blursobelyMat_cols_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_blursobelyMat_cols_V_channel.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_blursobelyMat_data_stream_0_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_blursobelyMat_rows_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_blursobelyMat_rows_V_channel.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_dilateMat_cols_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_dilateMat_cols_V_channel.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_dilateMat_data_stream_0_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_dilateMat_rows_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_dilateMat_rows_V_channel.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_grayMat_cols_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_grayMat_data_stream_0_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_grayMat_rows_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_inMat_cols_V_channel.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_inMat_cols_V_channel1.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_inMat_data_stream_0_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_inMat_data_stream_1_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_inMat_data_stream_2_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_inMat_rows_V_channel.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_inMat_rows_V_channel1.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_nmsupressionMat_cols_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_nmsupressionMat_data_stream_0.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_nmsupressionMat_rows_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_outMat_cols_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_outMat_data_stream_0_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_outMat_rows_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_sobelxMat_data_stream_0_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_sobelyMat_data_stream_0_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_threshMat_cols_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_threshMat_data_stream_0_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/FIFO_toThreshold_threshMat_rows_V.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_AXIvideo2Mat.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_Block_proc.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_CvtColor.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_Dilate_0_0_1080_1920_1.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_Dilate_0_0_1080_1920_s.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_Duplicate_1080_1920_0_0_s.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_GaussianBlur.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_Loop_GradientLoop_proc.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_Loop_LineBufferLoop_proc.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_Mat2AXIvideo_8_1080_1920_0_s.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_Sobel.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_Sobel_1.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold_Threshold_1080_1920_0_0_s.v
  C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold.v
}
read_xdc C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold.xdc
set_property used_in_implementation false [get_files C:/Xilinx/Projects/threshold_IP_hls/threshold_IP/solution1/impl/verilog/toThreshold.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file toThreshold.hwdef }
synth_design -top toThreshold -part xc7z020clg484-1 -no_iobuf -mode out_of_context
write_checkpoint -noxdef toThreshold.dcp
catch { report_utilization -file toThreshold_utilization_synth.rpt -pb toThreshold_utilization_synth.pb }
