// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "toThreshold_borderInterpolate.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic toThreshold_borderInterpolate::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<1> toThreshold_borderInterpolate::ap_const_lv1_0 = "0";
const sc_lv<32> toThreshold_borderInterpolate::ap_const_lv32_C = "1100";
const sc_lv<1> toThreshold_borderInterpolate::ap_const_lv1_1 = "1";
const sc_lv<4> toThreshold_borderInterpolate::ap_const_lv4_1 = "1";
const sc_lv<4> toThreshold_borderInterpolate::ap_const_lv4_2 = "10";
const sc_lv<4> toThreshold_borderInterpolate::ap_const_lv4_4 = "100";
const sc_lv<13> toThreshold_borderInterpolate::ap_const_lv13_1FFF = "1111111111111";
const sc_lv<4> toThreshold_borderInterpolate::ap_const_lv4_0 = "0000";
const sc_lv<13> toThreshold_borderInterpolate::ap_const_lv13_0 = "0000000000000";
const sc_lv<12> toThreshold_borderInterpolate::ap_const_lv12_1 = "1";
const sc_lv<14> toThreshold_borderInterpolate::ap_const_lv14_3FFE = "11111111111110";
const sc_lv<15> toThreshold_borderInterpolate::ap_const_lv15_0 = "000000000000000";
const sc_logic toThreshold_borderInterpolate::ap_const_logic_0 = sc_dt::Log_0;

toThreshold_borderInterpolate::toThreshold_borderInterpolate(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_ce );
    sensitive << ( sel_tmp51_reg_514 );
    sensitive << ( p_p2_cast_fu_362_p1 );
    sensitive << ( sel_tmp42_fu_392_p3 );

    SC_METHOD(thread_len_cast1_cast_fu_73_p1);
    sensitive << ( len );

    SC_METHOD(thread_or_cond_fu_83_p2);
    sensitive << ( tmp_1_fu_77_p2 );
    sensitive << ( rev_fu_67_p2 );

    SC_METHOD(thread_p_assign_1_fu_115_p2);
    sensitive << ( p );

    SC_METHOD(thread_p_assign_2_fu_201_p2);
    sensitive << ( tmp_73_cast_fu_183_p1 );
    sensitive << ( tmp_74_cast_fu_197_p1 );

    SC_METHOD(thread_p_assign_3_fu_207_p2);
    sensitive << ( p_read_reg_412 );

    SC_METHOD(thread_p_assign_4_fu_233_p2);
    sensitive << ( tmp_17_fu_227_p2 );
    sensitive << ( p_p2_cast_cast_fu_218_p1 );

    SC_METHOD(thread_p_assign_cast_fu_151_p1);
    sensitive << ( p_assign_fu_144_p3 );

    SC_METHOD(thread_p_assign_fu_144_p3);
    sensitive << ( tmp_151_reg_440 );
    sensitive << ( tmp_4_fu_139_p2 );

    SC_METHOD(thread_p_cast1_cast_fu_353_p1);
    sensitive << ( ap_reg_ppstg_p_read_reg_412_pp0_it1 );

    SC_METHOD(thread_p_p2_cast_cast_fu_218_p1);
    sensitive << ( p_p2_fu_212_p3 );

    SC_METHOD(thread_p_p2_cast_fu_362_p1);
    sensitive << ( p_p2_reg_484 );

    SC_METHOD(thread_p_p2_fu_212_p3);
    sensitive << ( p_read_reg_412 );
    sensitive << ( tmp_151_reg_440 );
    sensitive << ( p_assign_3_fu_207_p2 );

    SC_METHOD(thread_p_p3_cast_cast_fu_359_p1);
    sensitive << ( p_p3_reg_479 );

    SC_METHOD(thread_p_p3_fu_170_p3);
    sensitive << ( p_read_reg_412 );
    sensitive << ( tmp_11_reg_464 );

    SC_METHOD(thread_p_p_cast2_cast_fu_356_p1);
    sensitive << ( p_p_reg_474 );

    SC_METHOD(thread_p_p_fu_160_p3);
    sensitive << ( p_read_reg_412 );
    sensitive << ( tmp_151_reg_440 );
    sensitive << ( p_assign_1_reg_459 );

    SC_METHOD(thread_rev_fu_67_p2);
    sensitive << ( tmp_fu_59_p3 );

    SC_METHOD(thread_sel_tmp10_fu_288_p2);
    sensitive << ( sel_tmp8_fu_276_p2 );
    sensitive << ( sel_tmp9_fu_282_p2 );

    SC_METHOD(thread_sel_tmp11_fu_294_p3);
    sensitive << ( sel_tmp10_fu_288_p2 );
    sensitive << ( p_assign_2_fu_201_p2 );
    sensitive << ( sel_tmp2_cast_fu_251_p1 );

    SC_METHOD(thread_sel_tmp16_demorgan_fu_302_p2);
    sensitive << ( tmp_5_reg_447 );
    sensitive << ( sel_tmp5_demorgan_fu_255_p2 );

    SC_METHOD(thread_sel_tmp18_demorgan_fu_307_p2);
    sensitive << ( tmp_7_reg_453 );
    sensitive << ( sel_tmp16_demorgan_fu_302_p2 );

    SC_METHOD(thread_sel_tmp19_fu_365_p3);
    sensitive << ( sel_tmp11_reg_489 );
    sensitive << ( sel_tmp18_demorgan_reg_494 );
    sensitive << ( p_p3_cast_cast_fu_359_p1 );

    SC_METHOD(thread_sel_tmp1_fu_239_p2);
    sensitive << ( tmp_2_reg_434 );
    sensitive << ( sel_tmp_reg_469 );

    SC_METHOD(thread_sel_tmp20_fu_371_p3);
    sensitive << ( ap_reg_ppstg_or_cond_reg_428_pp0_it1 );
    sensitive << ( p_cast1_cast_fu_353_p1 );
    sensitive << ( sel_tmp19_fu_365_p3 );

    SC_METHOD(thread_sel_tmp25_fu_312_p2);
    sensitive << ( tmp_6_fu_155_p2 );
    sensitive << ( sel_tmp6_fu_265_p2 );

    SC_METHOD(thread_sel_tmp26_fu_378_p3);
    sensitive << ( sel_tmp25_reg_499 );
    sensitive << ( sel_tmp20_fu_371_p3 );

    SC_METHOD(thread_sel_tmp2_cast_fu_251_p1);
    sensitive << ( sel_tmp2_fu_243_p3 );

    SC_METHOD(thread_sel_tmp2_fu_243_p3);
    sensitive << ( sel_tmp1_fu_239_p2 );
    sensitive << ( p_assign_cast_fu_151_p1 );
    sensitive << ( p_assign_4_fu_233_p2 );

    SC_METHOD(thread_sel_tmp33_fu_318_p2);
    sensitive << ( tmp_9_fu_165_p2 );
    sensitive << ( sel_tmp8_fu_276_p2 );

    SC_METHOD(thread_sel_tmp34_fu_385_p3);
    sensitive << ( sel_tmp33_reg_504 );
    sensitive << ( p_p_cast2_cast_fu_356_p1 );
    sensitive << ( sel_tmp26_fu_378_p3 );

    SC_METHOD(thread_sel_tmp39_fu_324_p2);
    sensitive << ( sel_tmp16_demorgan_fu_302_p2 );

    SC_METHOD(thread_sel_tmp40_fu_330_p2);
    sensitive << ( tmp_7_reg_453 );
    sensitive << ( sel_tmp39_fu_324_p2 );

    SC_METHOD(thread_sel_tmp41_fu_335_p2);
    sensitive << ( tmp_6_fu_155_p2 );
    sensitive << ( sel_tmp40_fu_330_p2 );

    SC_METHOD(thread_sel_tmp42_fu_392_p3);
    sensitive << ( sel_tmp41_reg_509 );
    sensitive << ( sel_tmp34_fu_385_p3 );

    SC_METHOD(thread_sel_tmp51_fu_347_p2);
    sensitive << ( sel_tmp40_fu_330_p2 );
    sensitive << ( tmp53_fu_341_p2 );

    SC_METHOD(thread_sel_tmp5_demorgan_fu_255_p2);
    sensitive << ( or_cond_reg_428 );
    sensitive << ( tmp_2_reg_434 );

    SC_METHOD(thread_sel_tmp5_fu_259_p2);
    sensitive << ( sel_tmp5_demorgan_fu_255_p2 );

    SC_METHOD(thread_sel_tmp6_fu_265_p2);
    sensitive << ( tmp_5_reg_447 );
    sensitive << ( sel_tmp5_fu_259_p2 );

    SC_METHOD(thread_sel_tmp7_fu_270_p2);
    sensitive << ( tmp_6_fu_155_p2 );

    SC_METHOD(thread_sel_tmp8_fu_276_p2);
    sensitive << ( sel_tmp6_fu_265_p2 );
    sensitive << ( sel_tmp7_fu_270_p2 );

    SC_METHOD(thread_sel_tmp9_fu_282_p2);
    sensitive << ( tmp_9_fu_165_p2 );

    SC_METHOD(thread_sel_tmp_fu_133_p2);
    sensitive << ( tmp_fu_59_p3 );
    sensitive << ( tmp_1_not_fu_127_p2 );

    SC_METHOD(thread_tmp53_fu_341_p2);
    sensitive << ( sel_tmp7_fu_270_p2 );
    sensitive << ( tmp_15_fu_222_p2 );

    SC_METHOD(thread_tmp_11_fu_121_p2);
    sensitive << ( borderType );
    sensitive << ( ap_ce );

    SC_METHOD(thread_tmp_12_fu_176_p3);
    sensitive << ( len_read_reg_406 );

    SC_METHOD(thread_tmp_13_fu_191_p2);
    sensitive << ( p_p_fu_160_p3 );

    SC_METHOD(thread_tmp_15_fu_222_p2);
    sensitive << ( ap_ce );
    sensitive << ( len_cast1_cast_reg_421 );
    sensitive << ( p_p2_fu_212_p3 );

    SC_METHOD(thread_tmp_17_fu_227_p2);
    sensitive << ( tmp_73_cast_cast_fu_187_p1 );

    SC_METHOD(thread_tmp_1_fu_77_p2);
    sensitive << ( p );
    sensitive << ( ap_ce );
    sensitive << ( len_cast1_cast_fu_73_p1 );

    SC_METHOD(thread_tmp_1_not_fu_127_p2);
    sensitive << ( tmp_1_fu_77_p2 );

    SC_METHOD(thread_tmp_2_fu_89_p2);
    sensitive << ( borderType );
    sensitive << ( ap_ce );

    SC_METHOD(thread_tmp_4_fu_139_p2);
    sensitive << ( len_cast1_cast_reg_421 );

    SC_METHOD(thread_tmp_5_fu_103_p2);
    sensitive << ( borderType );
    sensitive << ( ap_ce );

    SC_METHOD(thread_tmp_6_fu_155_p2);
    sensitive << ( len_read_reg_406 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_tmp_73_cast_cast_fu_187_p1);
    sensitive << ( tmp_12_fu_176_p3 );

    SC_METHOD(thread_tmp_73_cast_fu_183_p1);
    sensitive << ( tmp_12_fu_176_p3 );

    SC_METHOD(thread_tmp_74_cast_fu_197_p1);
    sensitive << ( tmp_13_fu_191_p2 );

    SC_METHOD(thread_tmp_7_fu_109_p2);
    sensitive << ( borderType );
    sensitive << ( ap_ce );

    SC_METHOD(thread_tmp_9_fu_165_p2);
    sensitive << ( ap_ce );
    sensitive << ( len_cast1_cast_reg_421 );
    sensitive << ( p_p_fu_160_p3 );

    SC_METHOD(thread_tmp_fu_59_p3);
    sensitive << ( p );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "toThreshold_borderInterpolate_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, p, "(port)p");
    sc_trace(mVcdFile, len, "(port)len");
    sc_trace(mVcdFile, borderType, "(port)borderType");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, len_read_reg_406, "len_read_reg_406");
    sc_trace(mVcdFile, p_read_reg_412, "p_read_reg_412");
    sc_trace(mVcdFile, ap_reg_ppstg_p_read_reg_412_pp0_it1, "ap_reg_ppstg_p_read_reg_412_pp0_it1");
    sc_trace(mVcdFile, len_cast1_cast_fu_73_p1, "len_cast1_cast_fu_73_p1");
    sc_trace(mVcdFile, len_cast1_cast_reg_421, "len_cast1_cast_reg_421");
    sc_trace(mVcdFile, or_cond_fu_83_p2, "or_cond_fu_83_p2");
    sc_trace(mVcdFile, or_cond_reg_428, "or_cond_reg_428");
    sc_trace(mVcdFile, ap_reg_ppstg_or_cond_reg_428_pp0_it1, "ap_reg_ppstg_or_cond_reg_428_pp0_it1");
    sc_trace(mVcdFile, tmp_2_fu_89_p2, "tmp_2_fu_89_p2");
    sc_trace(mVcdFile, tmp_2_reg_434, "tmp_2_reg_434");
    sc_trace(mVcdFile, tmp_151_reg_440, "tmp_151_reg_440");
    sc_trace(mVcdFile, tmp_5_fu_103_p2, "tmp_5_fu_103_p2");
    sc_trace(mVcdFile, tmp_5_reg_447, "tmp_5_reg_447");
    sc_trace(mVcdFile, tmp_7_fu_109_p2, "tmp_7_fu_109_p2");
    sc_trace(mVcdFile, tmp_7_reg_453, "tmp_7_reg_453");
    sc_trace(mVcdFile, p_assign_1_fu_115_p2, "p_assign_1_fu_115_p2");
    sc_trace(mVcdFile, p_assign_1_reg_459, "p_assign_1_reg_459");
    sc_trace(mVcdFile, tmp_11_fu_121_p2, "tmp_11_fu_121_p2");
    sc_trace(mVcdFile, tmp_11_reg_464, "tmp_11_reg_464");
    sc_trace(mVcdFile, sel_tmp_fu_133_p2, "sel_tmp_fu_133_p2");
    sc_trace(mVcdFile, sel_tmp_reg_469, "sel_tmp_reg_469");
    sc_trace(mVcdFile, p_p_fu_160_p3, "p_p_fu_160_p3");
    sc_trace(mVcdFile, p_p_reg_474, "p_p_reg_474");
    sc_trace(mVcdFile, p_p3_fu_170_p3, "p_p3_fu_170_p3");
    sc_trace(mVcdFile, p_p3_reg_479, "p_p3_reg_479");
    sc_trace(mVcdFile, p_p2_fu_212_p3, "p_p2_fu_212_p3");
    sc_trace(mVcdFile, p_p2_reg_484, "p_p2_reg_484");
    sc_trace(mVcdFile, sel_tmp11_fu_294_p3, "sel_tmp11_fu_294_p3");
    sc_trace(mVcdFile, sel_tmp11_reg_489, "sel_tmp11_reg_489");
    sc_trace(mVcdFile, sel_tmp18_demorgan_fu_307_p2, "sel_tmp18_demorgan_fu_307_p2");
    sc_trace(mVcdFile, sel_tmp18_demorgan_reg_494, "sel_tmp18_demorgan_reg_494");
    sc_trace(mVcdFile, sel_tmp25_fu_312_p2, "sel_tmp25_fu_312_p2");
    sc_trace(mVcdFile, sel_tmp25_reg_499, "sel_tmp25_reg_499");
    sc_trace(mVcdFile, sel_tmp33_fu_318_p2, "sel_tmp33_fu_318_p2");
    sc_trace(mVcdFile, sel_tmp33_reg_504, "sel_tmp33_reg_504");
    sc_trace(mVcdFile, sel_tmp41_fu_335_p2, "sel_tmp41_fu_335_p2");
    sc_trace(mVcdFile, sel_tmp41_reg_509, "sel_tmp41_reg_509");
    sc_trace(mVcdFile, sel_tmp51_fu_347_p2, "sel_tmp51_fu_347_p2");
    sc_trace(mVcdFile, sel_tmp51_reg_514, "sel_tmp51_reg_514");
    sc_trace(mVcdFile, tmp_fu_59_p3, "tmp_fu_59_p3");
    sc_trace(mVcdFile, tmp_1_fu_77_p2, "tmp_1_fu_77_p2");
    sc_trace(mVcdFile, rev_fu_67_p2, "rev_fu_67_p2");
    sc_trace(mVcdFile, tmp_1_not_fu_127_p2, "tmp_1_not_fu_127_p2");
    sc_trace(mVcdFile, tmp_4_fu_139_p2, "tmp_4_fu_139_p2");
    sc_trace(mVcdFile, p_assign_fu_144_p3, "p_assign_fu_144_p3");
    sc_trace(mVcdFile, tmp_12_fu_176_p3, "tmp_12_fu_176_p3");
    sc_trace(mVcdFile, tmp_13_fu_191_p2, "tmp_13_fu_191_p2");
    sc_trace(mVcdFile, tmp_73_cast_fu_183_p1, "tmp_73_cast_fu_183_p1");
    sc_trace(mVcdFile, tmp_74_cast_fu_197_p1, "tmp_74_cast_fu_197_p1");
    sc_trace(mVcdFile, p_assign_3_fu_207_p2, "p_assign_3_fu_207_p2");
    sc_trace(mVcdFile, tmp_73_cast_cast_fu_187_p1, "tmp_73_cast_cast_fu_187_p1");
    sc_trace(mVcdFile, tmp_17_fu_227_p2, "tmp_17_fu_227_p2");
    sc_trace(mVcdFile, p_p2_cast_cast_fu_218_p1, "p_p2_cast_cast_fu_218_p1");
    sc_trace(mVcdFile, sel_tmp1_fu_239_p2, "sel_tmp1_fu_239_p2");
    sc_trace(mVcdFile, p_assign_cast_fu_151_p1, "p_assign_cast_fu_151_p1");
    sc_trace(mVcdFile, p_assign_4_fu_233_p2, "p_assign_4_fu_233_p2");
    sc_trace(mVcdFile, sel_tmp2_fu_243_p3, "sel_tmp2_fu_243_p3");
    sc_trace(mVcdFile, sel_tmp5_demorgan_fu_255_p2, "sel_tmp5_demorgan_fu_255_p2");
    sc_trace(mVcdFile, sel_tmp5_fu_259_p2, "sel_tmp5_fu_259_p2");
    sc_trace(mVcdFile, tmp_6_fu_155_p2, "tmp_6_fu_155_p2");
    sc_trace(mVcdFile, sel_tmp6_fu_265_p2, "sel_tmp6_fu_265_p2");
    sc_trace(mVcdFile, sel_tmp7_fu_270_p2, "sel_tmp7_fu_270_p2");
    sc_trace(mVcdFile, tmp_9_fu_165_p2, "tmp_9_fu_165_p2");
    sc_trace(mVcdFile, sel_tmp8_fu_276_p2, "sel_tmp8_fu_276_p2");
    sc_trace(mVcdFile, sel_tmp9_fu_282_p2, "sel_tmp9_fu_282_p2");
    sc_trace(mVcdFile, sel_tmp10_fu_288_p2, "sel_tmp10_fu_288_p2");
    sc_trace(mVcdFile, p_assign_2_fu_201_p2, "p_assign_2_fu_201_p2");
    sc_trace(mVcdFile, sel_tmp2_cast_fu_251_p1, "sel_tmp2_cast_fu_251_p1");
    sc_trace(mVcdFile, sel_tmp16_demorgan_fu_302_p2, "sel_tmp16_demorgan_fu_302_p2");
    sc_trace(mVcdFile, sel_tmp39_fu_324_p2, "sel_tmp39_fu_324_p2");
    sc_trace(mVcdFile, sel_tmp40_fu_330_p2, "sel_tmp40_fu_330_p2");
    sc_trace(mVcdFile, tmp_15_fu_222_p2, "tmp_15_fu_222_p2");
    sc_trace(mVcdFile, tmp53_fu_341_p2, "tmp53_fu_341_p2");
    sc_trace(mVcdFile, p_p3_cast_cast_fu_359_p1, "p_p3_cast_cast_fu_359_p1");
    sc_trace(mVcdFile, p_cast1_cast_fu_353_p1, "p_cast1_cast_fu_353_p1");
    sc_trace(mVcdFile, sel_tmp19_fu_365_p3, "sel_tmp19_fu_365_p3");
    sc_trace(mVcdFile, sel_tmp20_fu_371_p3, "sel_tmp20_fu_371_p3");
    sc_trace(mVcdFile, p_p_cast2_cast_fu_356_p1, "p_p_cast2_cast_fu_356_p1");
    sc_trace(mVcdFile, sel_tmp26_fu_378_p3, "sel_tmp26_fu_378_p3");
    sc_trace(mVcdFile, sel_tmp34_fu_385_p3, "sel_tmp34_fu_385_p3");
    sc_trace(mVcdFile, p_p2_cast_fu_362_p1, "p_p2_cast_fu_362_p1");
    sc_trace(mVcdFile, sel_tmp42_fu_392_p3, "sel_tmp42_fu_392_p3");
#endif

    }
}

toThreshold_borderInterpolate::~toThreshold_borderInterpolate() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void toThreshold_borderInterpolate::thread_ap_clk_no_reset_() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce.read())) {
        ap_reg_ppstg_or_cond_reg_428_pp0_it1 = or_cond_reg_428.read();
        ap_reg_ppstg_p_read_reg_412_pp0_it1 = p_read_reg_412.read();
        len_cast1_cast_reg_421 = len_cast1_cast_fu_73_p1.read();
        len_read_reg_406 = len.read();
        or_cond_reg_428 = or_cond_fu_83_p2.read();
        p_assign_1_reg_459 = p_assign_1_fu_115_p2.read();
        p_p2_reg_484 = p_p2_fu_212_p3.read();
        p_p_reg_474 = p_p_fu_160_p3.read();
        p_read_reg_412 = p.read();
        sel_tmp25_reg_499 = sel_tmp25_fu_312_p2.read();
        sel_tmp33_reg_504 = sel_tmp33_fu_318_p2.read();
        sel_tmp41_reg_509 = sel_tmp41_fu_335_p2.read();
        sel_tmp51_reg_514 = sel_tmp51_fu_347_p2.read();
        sel_tmp_reg_469 = sel_tmp_fu_133_p2.read();
        tmp_11_reg_464 = tmp_11_fu_121_p2.read();
        tmp_151_reg_440 = p.read().range(12, 12);
        tmp_2_reg_434 = tmp_2_fu_89_p2.read();
        tmp_5_reg_447 = tmp_5_fu_103_p2.read();
        tmp_7_reg_453 = tmp_7_fu_109_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_ce.read()) && esl_seteq<1,1,1>(or_cond_reg_428.read(), ap_const_lv1_0))) {
        p_p3_reg_479 = p_p3_fu_170_p3.read();
        sel_tmp11_reg_489 = sel_tmp11_fu_294_p3.read();
        sel_tmp18_demorgan_reg_494 = sel_tmp18_demorgan_fu_307_p2.read();
    }
}

void toThreshold_borderInterpolate::thread_ap_return() {
    ap_return = (!sel_tmp51_reg_514.read()[0].is_01())? sc_lv<15>(): ((sel_tmp51_reg_514.read()[0].to_bool())? p_p2_cast_fu_362_p1.read(): sel_tmp42_fu_392_p3.read());
}

void toThreshold_borderInterpolate::thread_len_cast1_cast_fu_73_p1() {
    len_cast1_cast_fu_73_p1 = esl_zext<13,12>(len.read());
}

void toThreshold_borderInterpolate::thread_or_cond_fu_83_p2() {
    or_cond_fu_83_p2 = (tmp_1_fu_77_p2.read() & rev_fu_67_p2.read());
}

void toThreshold_borderInterpolate::thread_p_assign_1_fu_115_p2() {
    p_assign_1_fu_115_p2 = (p.read() ^ ap_const_lv13_1FFF);
}

void toThreshold_borderInterpolate::thread_p_assign_2_fu_201_p2() {
    p_assign_2_fu_201_p2 = (!tmp_73_cast_fu_183_p1.read().is_01() || !tmp_74_cast_fu_197_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_73_cast_fu_183_p1.read()) + sc_bigint<15>(tmp_74_cast_fu_197_p1.read()));
}

void toThreshold_borderInterpolate::thread_p_assign_3_fu_207_p2() {
    p_assign_3_fu_207_p2 = (!ap_const_lv13_0.is_01() || !p_read_reg_412.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_biguint<13>(p_read_reg_412.read()));
}

void toThreshold_borderInterpolate::thread_p_assign_4_fu_233_p2() {
    p_assign_4_fu_233_p2 = (!tmp_17_fu_227_p2.read().is_01() || !p_p2_cast_cast_fu_218_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(tmp_17_fu_227_p2.read()) - sc_biguint<14>(p_p2_cast_cast_fu_218_p1.read()));
}

void toThreshold_borderInterpolate::thread_p_assign_cast_fu_151_p1() {
    p_assign_cast_fu_151_p1 = esl_sext<14,13>(p_assign_fu_144_p3.read());
}

void toThreshold_borderInterpolate::thread_p_assign_fu_144_p3() {
    p_assign_fu_144_p3 = (!tmp_151_reg_440.read()[0].is_01())? sc_lv<13>(): ((tmp_151_reg_440.read()[0].to_bool())? ap_const_lv13_0: tmp_4_fu_139_p2.read());
}

void toThreshold_borderInterpolate::thread_p_cast1_cast_fu_353_p1() {
    p_cast1_cast_fu_353_p1 = esl_sext<15,13>(ap_reg_ppstg_p_read_reg_412_pp0_it1.read());
}

void toThreshold_borderInterpolate::thread_p_p2_cast_cast_fu_218_p1() {
    p_p2_cast_cast_fu_218_p1 = esl_zext<14,13>(p_p2_fu_212_p3.read());
}

void toThreshold_borderInterpolate::thread_p_p2_cast_fu_362_p1() {
    p_p2_cast_fu_362_p1 = esl_zext<15,13>(p_p2_reg_484.read());
}

void toThreshold_borderInterpolate::thread_p_p2_fu_212_p3() {
    p_p2_fu_212_p3 = (!tmp_151_reg_440.read()[0].is_01())? sc_lv<13>(): ((tmp_151_reg_440.read()[0].to_bool())? p_assign_3_fu_207_p2.read(): p_read_reg_412.read());
}

void toThreshold_borderInterpolate::thread_p_p3_cast_cast_fu_359_p1() {
    p_p3_cast_cast_fu_359_p1 = esl_sext<15,13>(p_p3_reg_479.read());
}

void toThreshold_borderInterpolate::thread_p_p3_fu_170_p3() {
    p_p3_fu_170_p3 = (!tmp_11_reg_464.read()[0].is_01())? sc_lv<13>(): ((tmp_11_reg_464.read()[0].to_bool())? ap_const_lv13_1FFF: p_read_reg_412.read());
}

void toThreshold_borderInterpolate::thread_p_p_cast2_cast_fu_356_p1() {
    p_p_cast2_cast_fu_356_p1 = esl_sext<15,13>(p_p_reg_474.read());
}

void toThreshold_borderInterpolate::thread_p_p_fu_160_p3() {
    p_p_fu_160_p3 = (!tmp_151_reg_440.read()[0].is_01())? sc_lv<13>(): ((tmp_151_reg_440.read()[0].to_bool())? p_assign_1_reg_459.read(): p_read_reg_412.read());
}

void toThreshold_borderInterpolate::thread_rev_fu_67_p2() {
    rev_fu_67_p2 = (tmp_fu_59_p3.read() ^ ap_const_lv1_1);
}

void toThreshold_borderInterpolate::thread_sel_tmp10_fu_288_p2() {
    sel_tmp10_fu_288_p2 = (sel_tmp8_fu_276_p2.read() & sel_tmp9_fu_282_p2.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp11_fu_294_p3() {
    sel_tmp11_fu_294_p3 = (!sel_tmp10_fu_288_p2.read()[0].is_01())? sc_lv<15>(): ((sel_tmp10_fu_288_p2.read()[0].to_bool())? p_assign_2_fu_201_p2.read(): sel_tmp2_cast_fu_251_p1.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp16_demorgan_fu_302_p2() {
    sel_tmp16_demorgan_fu_302_p2 = (sel_tmp5_demorgan_fu_255_p2.read() | tmp_5_reg_447.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp18_demorgan_fu_307_p2() {
    sel_tmp18_demorgan_fu_307_p2 = (sel_tmp16_demorgan_fu_302_p2.read() | tmp_7_reg_453.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp19_fu_365_p3() {
    sel_tmp19_fu_365_p3 = (!sel_tmp18_demorgan_reg_494.read()[0].is_01())? sc_lv<15>(): ((sel_tmp18_demorgan_reg_494.read()[0].to_bool())? sel_tmp11_reg_489.read(): p_p3_cast_cast_fu_359_p1.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp1_fu_239_p2() {
    sel_tmp1_fu_239_p2 = (tmp_2_reg_434.read() & sel_tmp_reg_469.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp20_fu_371_p3() {
    sel_tmp20_fu_371_p3 = (!ap_reg_ppstg_or_cond_reg_428_pp0_it1.read()[0].is_01())? sc_lv<15>(): ((ap_reg_ppstg_or_cond_reg_428_pp0_it1.read()[0].to_bool())? p_cast1_cast_fu_353_p1.read(): sel_tmp19_fu_365_p3.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp25_fu_312_p2() {
    sel_tmp25_fu_312_p2 = (sel_tmp6_fu_265_p2.read() & tmp_6_fu_155_p2.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp26_fu_378_p3() {
    sel_tmp26_fu_378_p3 = (!sel_tmp25_reg_499.read()[0].is_01())? sc_lv<15>(): ((sel_tmp25_reg_499.read()[0].to_bool())? ap_const_lv15_0: sel_tmp20_fu_371_p3.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp2_cast_fu_251_p1() {
    sel_tmp2_cast_fu_251_p1 = esl_sext<15,14>(sel_tmp2_fu_243_p3.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp2_fu_243_p3() {
    sel_tmp2_fu_243_p3 = (!sel_tmp1_fu_239_p2.read()[0].is_01())? sc_lv<14>(): ((sel_tmp1_fu_239_p2.read()[0].to_bool())? p_assign_cast_fu_151_p1.read(): p_assign_4_fu_233_p2.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp33_fu_318_p2() {
    sel_tmp33_fu_318_p2 = (sel_tmp8_fu_276_p2.read() & tmp_9_fu_165_p2.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp34_fu_385_p3() {
    sel_tmp34_fu_385_p3 = (!sel_tmp33_reg_504.read()[0].is_01())? sc_lv<15>(): ((sel_tmp33_reg_504.read()[0].to_bool())? p_p_cast2_cast_fu_356_p1.read(): sel_tmp26_fu_378_p3.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp39_fu_324_p2() {
    sel_tmp39_fu_324_p2 = (sel_tmp16_demorgan_fu_302_p2.read() ^ ap_const_lv1_1);
}

void toThreshold_borderInterpolate::thread_sel_tmp40_fu_330_p2() {
    sel_tmp40_fu_330_p2 = (tmp_7_reg_453.read() & sel_tmp39_fu_324_p2.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp41_fu_335_p2() {
    sel_tmp41_fu_335_p2 = (sel_tmp40_fu_330_p2.read() & tmp_6_fu_155_p2.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp42_fu_392_p3() {
    sel_tmp42_fu_392_p3 = (!sel_tmp41_reg_509.read()[0].is_01())? sc_lv<15>(): ((sel_tmp41_reg_509.read()[0].to_bool())? ap_const_lv15_0: sel_tmp34_fu_385_p3.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp51_fu_347_p2() {
    sel_tmp51_fu_347_p2 = (tmp53_fu_341_p2.read() & sel_tmp40_fu_330_p2.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp5_demorgan_fu_255_p2() {
    sel_tmp5_demorgan_fu_255_p2 = (or_cond_reg_428.read() | tmp_2_reg_434.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp5_fu_259_p2() {
    sel_tmp5_fu_259_p2 = (sel_tmp5_demorgan_fu_255_p2.read() ^ ap_const_lv1_1);
}

void toThreshold_borderInterpolate::thread_sel_tmp6_fu_265_p2() {
    sel_tmp6_fu_265_p2 = (tmp_5_reg_447.read() & sel_tmp5_fu_259_p2.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp7_fu_270_p2() {
    sel_tmp7_fu_270_p2 = (tmp_6_fu_155_p2.read() ^ ap_const_lv1_1);
}

void toThreshold_borderInterpolate::thread_sel_tmp8_fu_276_p2() {
    sel_tmp8_fu_276_p2 = (sel_tmp6_fu_265_p2.read() & sel_tmp7_fu_270_p2.read());
}

void toThreshold_borderInterpolate::thread_sel_tmp9_fu_282_p2() {
    sel_tmp9_fu_282_p2 = (tmp_9_fu_165_p2.read() ^ ap_const_lv1_1);
}

void toThreshold_borderInterpolate::thread_sel_tmp_fu_133_p2() {
    sel_tmp_fu_133_p2 = (tmp_fu_59_p3.read() | tmp_1_not_fu_127_p2.read());
}

void toThreshold_borderInterpolate::thread_tmp53_fu_341_p2() {
    tmp53_fu_341_p2 = (tmp_15_fu_222_p2.read() & sel_tmp7_fu_270_p2.read());
}

void toThreshold_borderInterpolate::thread_tmp_11_fu_121_p2() {
    tmp_11_fu_121_p2 = (!borderType.read().is_01() || !ap_const_lv4_0.is_01())? sc_lv<1>(): sc_lv<1>(borderType.read() == ap_const_lv4_0);
}

void toThreshold_borderInterpolate::thread_tmp_12_fu_176_p3() {
    tmp_12_fu_176_p3 = esl_concat<12,1>(len_read_reg_406.read(), ap_const_lv1_0);
}

void toThreshold_borderInterpolate::thread_tmp_13_fu_191_p2() {
    tmp_13_fu_191_p2 = (p_p_fu_160_p3.read() ^ ap_const_lv13_1FFF);
}

void toThreshold_borderInterpolate::thread_tmp_15_fu_222_p2() {
    tmp_15_fu_222_p2 = (!p_p2_fu_212_p3.read().is_01() || !len_cast1_cast_reg_421.read().is_01())? sc_lv<1>(): (sc_biguint<13>(p_p2_fu_212_p3.read()) < sc_biguint<13>(len_cast1_cast_reg_421.read()));
}

void toThreshold_borderInterpolate::thread_tmp_17_fu_227_p2() {
    tmp_17_fu_227_p2 = (!tmp_73_cast_cast_fu_187_p1.read().is_01() || !ap_const_lv14_3FFE.is_01())? sc_lv<14>(): (sc_biguint<14>(tmp_73_cast_cast_fu_187_p1.read()) + sc_bigint<14>(ap_const_lv14_3FFE));
}

void toThreshold_borderInterpolate::thread_tmp_1_fu_77_p2() {
    tmp_1_fu_77_p2 = (!len_cast1_cast_fu_73_p1.read().is_01() || !p.read().is_01())? sc_lv<1>(): (sc_bigint<13>(len_cast1_cast_fu_73_p1.read()) > sc_bigint<13>(p.read()));
}

void toThreshold_borderInterpolate::thread_tmp_1_not_fu_127_p2() {
    tmp_1_not_fu_127_p2 = (tmp_1_fu_77_p2.read() ^ ap_const_lv1_1);
}

void toThreshold_borderInterpolate::thread_tmp_2_fu_89_p2() {
    tmp_2_fu_89_p2 = (!borderType.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<1>(): sc_lv<1>(borderType.read() == ap_const_lv4_1);
}

void toThreshold_borderInterpolate::thread_tmp_4_fu_139_p2() {
    tmp_4_fu_139_p2 = (!len_cast1_cast_reg_421.read().is_01() || !ap_const_lv13_1FFF.is_01())? sc_lv<13>(): (sc_biguint<13>(len_cast1_cast_reg_421.read()) + sc_bigint<13>(ap_const_lv13_1FFF));
}

void toThreshold_borderInterpolate::thread_tmp_5_fu_103_p2() {
    tmp_5_fu_103_p2 = (!borderType.read().is_01() || !ap_const_lv4_2.is_01())? sc_lv<1>(): sc_lv<1>(borderType.read() == ap_const_lv4_2);
}

void toThreshold_borderInterpolate::thread_tmp_6_fu_155_p2() {
    tmp_6_fu_155_p2 = (!len_read_reg_406.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<1>(): sc_lv<1>(len_read_reg_406.read() == ap_const_lv12_1);
}

void toThreshold_borderInterpolate::thread_tmp_73_cast_cast_fu_187_p1() {
    tmp_73_cast_cast_fu_187_p1 = esl_zext<14,13>(tmp_12_fu_176_p3.read());
}

void toThreshold_borderInterpolate::thread_tmp_73_cast_fu_183_p1() {
    tmp_73_cast_fu_183_p1 = esl_zext<15,13>(tmp_12_fu_176_p3.read());
}

void toThreshold_borderInterpolate::thread_tmp_74_cast_fu_197_p1() {
    tmp_74_cast_fu_197_p1 = esl_sext<15,13>(tmp_13_fu_191_p2.read());
}

void toThreshold_borderInterpolate::thread_tmp_7_fu_109_p2() {
    tmp_7_fu_109_p2 = (!borderType.read().is_01() || !ap_const_lv4_4.is_01())? sc_lv<1>(): sc_lv<1>(borderType.read() == ap_const_lv4_4);
}

void toThreshold_borderInterpolate::thread_tmp_9_fu_165_p2() {
    tmp_9_fu_165_p2 = (!p_p_fu_160_p3.read().is_01() || !len_cast1_cast_reg_421.read().is_01())? sc_lv<1>(): (sc_bigint<13>(p_p_fu_160_p3.read()) < sc_bigint<13>(len_cast1_cast_reg_421.read()));
}

void toThreshold_borderInterpolate::thread_tmp_fu_59_p3() {
    tmp_fu_59_p3 = p.read().range(12, 12);
}

}

