// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _toThreshold_Duplicate_1080_1920_0_0_s_HH_
#define _toThreshold_Duplicate_1080_1920_0_0_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct toThreshold_Duplicate_1080_1920_0_0_s : public sc_module {
    // Port declarations 22
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<12> > src_rows_V_read;
    sc_in< sc_lv<12> > src_cols_V_read;
    sc_in< sc_lv<8> > src_data_stream_V_dout;
    sc_in< sc_logic > src_data_stream_V_empty_n;
    sc_out< sc_logic > src_data_stream_V_read;
    sc_in< sc_lv<12> > dst1_rows_V_read;
    sc_in< sc_lv<12> > dst1_cols_V_read;
    sc_out< sc_lv<8> > dst1_data_stream_V_din;
    sc_in< sc_logic > dst1_data_stream_V_full_n;
    sc_out< sc_logic > dst1_data_stream_V_write;
    sc_in< sc_lv<12> > dst2_rows_V_read;
    sc_in< sc_lv<12> > dst2_cols_V_read;
    sc_out< sc_lv<8> > dst2_data_stream_V_din;
    sc_in< sc_logic > dst2_data_stream_V_full_n;
    sc_out< sc_logic > dst2_data_stream_V_write;


    // Module declarations
    toThreshold_Duplicate_1080_1920_0_0_s(sc_module_name name);
    SC_HAS_PROCESS(toThreshold_Duplicate_1080_1920_0_0_s);

    ~toThreshold_Duplicate_1080_1920_0_0_s();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_23;
    sc_signal< sc_lv<11> > p_4_reg_143;
    sc_signal< bool > ap_sig_bdd_55;
    sc_signal< sc_lv<1> > exitcond4_fu_159_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_67;
    sc_signal< sc_lv<11> > i_V_fu_164_p2;
    sc_signal< sc_lv<11> > i_V_reg_199;
    sc_signal< sc_lv<1> > exitcond_fu_174_p2;
    sc_signal< sc_lv<1> > exitcond_reg_204;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_2;
    sc_signal< bool > ap_sig_bdd_78;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< bool > ap_sig_bdd_92;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_lv<11> > j_V_fu_179_p2;
    sc_signal< sc_lv<11> > p_s_reg_132;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_3;
    sc_signal< bool > ap_sig_bdd_116;
    sc_signal< sc_lv<12> > p_cast_fu_155_p1;
    sc_signal< sc_lv<12> > p_4_cast_fu_170_p1;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_st1_fsm_0;
    static const sc_lv<4> ap_ST_st2_fsm_1;
    static const sc_lv<4> ap_ST_pp0_stg0_fsm_2;
    static const sc_lv<4> ap_ST_st5_fsm_3;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<11> ap_const_lv11_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_116();
    void thread_ap_sig_bdd_23();
    void thread_ap_sig_bdd_55();
    void thread_ap_sig_bdd_67();
    void thread_ap_sig_bdd_78();
    void thread_ap_sig_bdd_92();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_2();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st5_fsm_3();
    void thread_dst1_data_stream_V_din();
    void thread_dst1_data_stream_V_write();
    void thread_dst2_data_stream_V_din();
    void thread_dst2_data_stream_V_write();
    void thread_exitcond4_fu_159_p2();
    void thread_exitcond_fu_174_p2();
    void thread_i_V_fu_164_p2();
    void thread_j_V_fu_179_p2();
    void thread_p_4_cast_fu_170_p1();
    void thread_p_cast_fu_155_p1();
    void thread_src_data_stream_V_read();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
